I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 528, in script
    ad "Правда, послушай маму, Рейчел. Это же выпускной вечер. Нельзя портить его себе только потому, что у тебя нет партнёра для танцев."
Exception: Sayer 'ad' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 528, in script
    ad "Правда, послушай маму, Рейчел. Это же выпускной вечер. Нельзя портить его себе только потому, что у тебя нет партнёра для танцев."
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\lalka\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'ad' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
In the Shade of the Walnut Tree 1.0
Thu Mar 13 22:02:47 2025
